# Generated by Django 2.0.1 on 2018-02-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=79)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=79)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Lista')),
            ],
            options={
                'verbose_name_plural': 'Menu itens',
            },
        ),
        migrations.CreateModel(
            name='MenuPasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=79)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.MenuPasta'),
        ),
        migrations.AddField(
            model_name='item',
            name='listas',
            field=models.ManyToManyField(to='catalogo.Lista'),
        ),
    ]
