# Generated by Django 2.0.1 on 2018-02-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20180207_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='listas',
            field=models.ManyToManyField(blank=True, to='catalogo.Lista'),
        ),
    ]
