# Generated by Django 2.0.1 on 2018-02-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20180207_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['produto__codigo'], 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='lista',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Menu itens'},
        ),
        migrations.AlterModelOptions(
            name='menupasta',
            options={'ordering': ['nome']},
        ),
    ]
