# Generated by Django 2.0.1 on 2018-02-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_empresa_contato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['user__username']},
        ),
    ]
