# Generated by Django 2.0.1 on 2018-02-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_auto_20180202_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cadastro_estadual',
            field=models.CharField(blank=True, max_length=35, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cadastro_municipal',
            field=models.CharField(blank=True, max_length=35, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cadastro_nacional',
            field=models.CharField(blank=True, max_length=35, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(blank=True, max_length=31, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='moeda',
            name='codigo',
            field=models.CharField(max_length=6, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=63, verbose_name='Código'),
        ),
    ]
