# Generated by Django 2.0.1 on 2018-02-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_auto_20180203_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['codigo']},
        ),
    ]
