# Generated by Django 2.0.1 on 2018-02-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_auto_20180204_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
