# Generated by Django 2.0.1 on 2018-02-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_empresa_bairro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moeda',
            options={'ordering': ['codigo']},
        ),
        migrations.AddField(
            model_name='configuracao',
            name='moeda_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.Moeda'),
        ),
    ]
