# Generated by Django 2.0.1 on 2018-01-30 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemdelinha',
            options={'verbose_name_plural': 'Itens de Linha'},
        ),
    ]
