# Generated by Django 2.0.1 on 2018-02-03 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0005_auto_20180203_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Transações'},
        ),
        migrations.AlterField(
            model_name='itemdelinha',
            name='transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='movimento.Transacao'),
        ),
    ]
