# Generated by Django 2.0.1 on 2018-02-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_auto_20180203_1722'),
        ('movimento', '0006_auto_20180203_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='moeda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.Moeda'),
        ),
    ]
