# Generated by Django 2.0.1 on 2018-02-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0007_transacao_moeda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdelinha',
            name='moeda',
        ),
    ]
