# Generated by Django 2.0.1 on 2018-02-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0008_remove_itemdelinha_moeda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdelinha',
            name='qtde',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
