# Generated by Django 2.0.1 on 2018-02-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0009_auto_20180204_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdelinha',
            name='preco_unitario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
